# 각 서비스에서 사용할 워크플로우 예제
# 서비스 레포의 .github/workflows/build.yml 파일로 저장하여 사용

name: App CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  release:
    types:
      - released     # Pre-release → Release (PRD deploy)
      - prereleased  # Release → Pre-release (rollback)

permissions:
  contents: write
  packages: write

jobs:
  app:
    uses: now-start/workflow/.github/workflows/reusable-java-app.yaml@main
    with:
      service-name: your-service-name      # 선택 (기본값: 레포 이름)
      registry-org: ghcr.io/now-start      # 선택
      enable-dev: true                     # DEV+PRD 모드 (false면 PRD 전용)
    secrets:
      registry-password: ${{ secrets.GITHUB_TOKEN }}
