# 각 서비스에서 사용할 워크플로우 예제
# .github/workflows/build.yml 파일로 저장하여 사용

name: Build and Deploy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: write
  packages: write

jobs:
  build-and-deploy:
    if: github.event_name == 'push'
    uses: now-start/workflow/.github/workflows/reusable-java-build.yml@main
    # with 섹션은 기본값으로 충분합니다
    # service-name: 자동으로 레포 이름 사용
    # java-version: 기본값 '17' 사용
    # 필요시에만 아래 주석을 해제하여 사용:
    # with:
    #   service-name: custom-service-name
    #   java-version: '21'
    secrets:
      registry-password: ${{ secrets.GITHUB_TOKEN }}

  # PR에서는 빌드/테스트만 수행
  test-only:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Build and test
        run: ./gradlew build